### ISSUE TITLE
Add an option to let us customize shadows

### ISSUE THREAD

**Issue by ralppppy** [Jamyth/react-native-neu-element#3]
I want to increase shadow distance just a little bit more

**Comment by Jamyth** [comment]
Currently you can pass two object to customize the light shadow and  dark shadow.
But it is still in experimental, and only support NeuView at the moment

try passing the prop `customLightShadow` and `customDarkShadow`
the property you can use are:

- blur

- spread

- color

- offsetX

- offsetY

but for color, offsetX and Y, I suggest putting a ternary of handling inset view.
I am refactoring that part of code for easier implementation.

**Comment by Jamyth** [comment]
This feature will come in version 1.2, stay tuned

**Comment by Jamyth** [comment]
Please update react-native-neu-element to the latest version, this feature has been added, thank you.
`npm install --save react-native-neu-element@1.1.7`
or
`npm install --save react-native-neu-element`
